# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

# Require `revel` command (compiled later from vendor dir)
required = ["github.com/revel/cmd/revel"]
[[constraint]]
  name = "github.com/revel/cmd"
  version = "^0.14.1"

# Override version for transitive dependencies
# otherwise we fetch the latest.
[[override]]
  name = "github.com/revel/config"
  version = "^0.14.0"
[[override]]
  name = "github.com/revel/modules"
  version = "^0.14.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.0"

[[constraint]]
  name = "github.com/revel/revel"
  version = "^0.14.0"

[[constraint]]
  name = "github.com/youtube/vitess"
  revision = "98f9189aa016e2a3afafa9ff42cde55bde421d3c"

[[constraint]]
  name = "github.com/percona/go-mysql"
  revision = "373945f3aa5d8a990e5a63282f16366633d23c97"

[[constraint]]
  name = "github.com/percona/pmm"
  revision = "890bc6cddb845dce02cb92749b429617e6581dbe"

